/**
 * Export Utility for Reports, CSV, and JSON
 */

export function exportToCSV(filename, rows) {
  if (!rows || !rows.length) return;
  const keys = Object.keys(rows[0]);
  const csvContent = [
    keys.join(","),
    ...rows.map(row => keys.map(k => {
      let cell = row[k] === null || row[k] === undefined ? "" : String(row[k]);
      if (cell.includes(",") || cell.includes('"') || cell.includes("\n")) {
        cell = `"${cell.replace(/"/g, '""')}"`;
      }
      return cell;
    }).join(","))
  ].join("\r\n");

  downloadBlob(new Blob([csvContent], { type: "text/csv;charset=utf-8;" }), filename);
}

export function exportToJSON(filename, data) {
  const json = JSON.stringify(data, null, 2);
  downloadBlob(new Blob([json], { type: "application/json" }), filename);
}

export function printExecutiveReport(title, sections) {
  const win = window.open("", "_blank");
  if (!win) return;

  const content = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} — Sentinel AI Technical Report</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 40px; color: #111; line-height: 1.6; }
          h1 { font-size: 24px; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
          h2 { font-size: 18px; margin-top: 25px; border-bottom: 1px solid #ccc; padding-bottom: 6px; }
          .meta { font-size: 12px; color: #666; margin-bottom: 30px; }
          .metric-box { display: inline-block; border: 1px solid #ddd; padding: 12px 18px; margin: 8px 8px 8px 0; border-radius: 4px; background: #f9f9f9; }
          .metric-label { font-size: 11px; text-transform: uppercase; color: #666; letter-spacing: 0.5px; }
          .metric-value { font-size: 20px; font-weight: bold; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 13px; }
          th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
          th { background: #f2f2f2; font-weight: 600; }
          ul { margin-top: 8px; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="meta">Generated by SENTINEL AI Intelligence Platform • ${new Date().toLocaleString()}</div>
        ${sections.map(s => `
          <h2>${s.title}</h2>
          ${s.summary ? `<p>${s.summary}</p>` : ''}
          ${s.metrics ? `<div style="margin: 10px 0;">${s.metrics.map(m => `
            <div class="metric-box">
              <div class="metric-label">${m.label}</div>
              <div class="metric-value">${m.value}</div>
            </div>
          `).join('')}</div>` : ''}
          ${s.bullets ? `<ul>${s.bullets.map(b => `<li>${b}</li>`).join('')}</ul>` : ''}
        `).join('')}
      </body>
    </html>
  `;

  win.document.write(content);
  win.document.close();
  setTimeout(() => {
    win.print();
  }, 350);
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
